#region Source Code Information
/*===================================================================================
	 Application Name		:	MRCS
	 Project Name			:	Presentation.Client.DotNetCore
	 Project Description	:	
	 FrameworkVersion		:	net7.0
	===================================================================================
	 Copyright    © 2023 InfoSolve Co.,Ltd.  All rights reserved.
	 THIS CODE AND INFORMATION IS PROVIDED "AS IS" WITHOUT WARRANTY
	 OF ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT
	 LIMITED TO THE IMPLIED WARRANTIES OF MERCHANTABILITY AND
	 FITNESS FOR A PARTICULAR PURPOSE.
	===================================================================================
	 Created Date			:	3/9/2023 9:09:01 PM
	 Author					:	Aung Si Thu Htaik
	 Machine				:	KOPAUK-PC
	 User					:	aungs
	 Version				:	1.0.0.0
	===================================================================================
	 Changes History
	 Date		Updated Description		Updated by
	-----------------------------------------------------------------------------------
	------------------------------------------------------------------------------------
	===================================================================================*/
#endregion
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a InfoSolve Code Generater.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace TestGridSelectFile
{    
    
    
    using Microsoft.AspNetCore.Http;
    using System.Text.Json;

    public static class SessionExtensions
    {
        public static void SetObjectAsJson(this ISession session, string key, object value)
        {
            session.SetString(key, JsonSerializer.Serialize(value));
        }

        public static T GetObjectFromJson<T>(this ISession session, string key)
        {
            var value = session.GetString(key);

            return value == null ? default(T) : JsonSerializer.Deserialize<T>(value);
        }
    }
}

